### ISSUE TITLE
Copy() error running script

### ISSUE THREAD

**Issue by DarkxPunk** [cfinke/OSX-Messages-Exporter#23] opened 2024-03-10 17:37 UTC
I decided to give your script a try running `php ~/Downloads/OSX-Messages-Exporter-master/messages-exporter.php -o ~/Messages/` and what I assume was near the end got the following error:

> Warning: copy(): The first argument to copy() function cannot be a directory in ~/Downloads/OSX-Messages-Exporter-master/messages-exporter.php on line 696

I am not sure why any copy function was called on the directory storing the script.

Appreciate any guidance on how to resolve.

**Comment by cfinke** [comment] 2024-03-11 06:08
I've just pushed a commit that should address this. The root cause is that the script is trying to save an attachment (an image or other non-message content), but when it tries to calculate what the filename should be, it ends up blank. The change (https://github.com/cfinke/OSX-Messages-Exporter/commit/7fd8c57afb517b9ecb64f8fea5412d260467fdc2) will just skip that case and output an error message that might or might not be helpful in figuring out why it happened. If you get a helpful message, let me know what it was so I can try and fix it in a better way.

**Comment by DarkxPunk** [comment] 2024-03-12 21:13
Howdy, so it did throw a clearer error:

> ~/Library/Messages/Attachments/##/##/##.../Adobe Swatches is a directory, not a file. Found in message body ~/Library/Messages/Attachments/##/##/##.../Adobe Swatches.

Not sure why that is throwing an error.

For your reference, the [ReagentX](https://github.com/ReagentX/)/[imessage-exporter](https://github.com/ReagentX/imessage-exporter) seems to simply ignore the file and report as attachment not found. Maybe a solution would be to .zip the folder and link to that?

Look forward to your next update.

**Comment by almog-co** [comment] 2024-03-15 23:16
I don't agree with the committed solution of doing

```
if ( is_dir( $file_to_copy ) ) {
    die( $file_to_copy . " is a directory, not a file. Found in message body " . $message['content'] . "\n" );
}
```

This terminates the program when encountering the error. The error can be duplicated by sending someone a `.app` Mac application as it appears to be a file to Mac OS but is really a folder. I recommend switching to

```
if ( is_dir( $file_to_copy ) ) {
    echo( $file_to_copy . " is a directory, not a file. Found in message body " . $message['content'] . "\n" );
    continue;
}
``` 

so the error is noted but the exporter continues to run.

**Comment by cfinke** [comment] 2024-03-22 21:43
You're right; I've pushed the fix in 087b269.

**Comment by DarkxPunk** [comment] 2024-04-25 02:27
Apologies for the late follow up. The change appears to just echo the error and continue as expected.

Is there any plans to figure out how to handle folders or no?

**Comment by cfinke** [comment] 2024-07-24 13:57
If I had a good example of when an attachment points to a folder that I could reproduce, I could add support for folders, but I've never encountered it myself.

**Comment by DarkxPunk** [comment] 2024-07-24 19:32
> If I had a good example of when an attachment points to a folder that I could reproduce, I could add support for folders, but I've never encountered it myself.

What can I provide to help? I do have this happen with my Messages history.

**Comment by cfinke** [comment] 2024-07-25 16:12
Are you able to determine what kind of message results in the exporter trying to copy a directory? Or at least, what does it say when it outputs "Found in message body [...]"?

**Comment by DarkxPunk** [comment] 2024-07-25 17:04
This was the error:
`~/Library/Messages/Attachments/##/##/##.../Adobe Swatches is a directory, not a file. Found in message body `

But I can replicate it again and give you a full log if you'd like.

The Attached image shows the path. So as mentioned prior, maybe the solution would be when a directory is found and not a file, we zip that directory and then copy it. -- Also a bit of a side note, but it would be good if there was some sort of clear message when the scrip completes successfully and without errors, just for peace of mind.

<img width="1475" alt="Screenshot 2024-07-25 at 13 01 56" src="https://github.com/user-attachments/assets/59d8f8bd-40ed-4995-9232-cfa81252118c">

**Comment by cfinke** [comment] 2024-07-25 22:01
If you scroll through your messages with that person, can you tell what Messages showed for that message? i.e., what was the person trying to send to you (or what were you sending) that resulted in this directory being an attachment?

**Comment by DarkxPunk** [comment] 2024-07-25 22:03
Yes, it was me dragging that folder into iMessage on my Mac and sending it to someone.

When they download it, it downloads like a folder.

**Comment by cfinke** [comment] 2024-07-26 04:13
I had no idea you could do that; thanks for the info. Zipping the folder does seem like a reasonable thing to do; I'll work on that.

**Comment by cfinke** [comment] 2024-07-31 05:47
Ok, I've committed something that at least works for me. It zips the directory and links to it in the exported chat.

Give it a shot and let me know whether it works for you.

**Closed** 2024-07-31 05:47 UTC
